services:
  - type: web
    name: popkid-bot
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: SESSION_ID
        sync: false
      - key: OCR_API_KEY
        sync: false
